config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :members, only: [:new, :create, :destroy]
    resources :chatrooms, only: [:new, :create]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post "/users/:nickname/members/new", to: "members#new_member", as: "new_member_user"
  get '/users/:nickname', to: 'users#show', as: 'user'
  patch "/members/:id/accept", to: "members#accept", as: "accept"
  patch "/members/:id/reject", to: "members#reject", as: "reject"
  patch "/members/:id/check", to: "members#check", as: "check"
  get "/dashboard", to: "users#dashboard", as: "dashboard"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :members
  validates :name, presence: true
  has_one :chatroom, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]

  def show
    @member = Member.new
    @members_pending = 0
    current_user.groups.each do |group|
      @members_pending += group.members.count { |member| member.status == "pending" }
    end

    @is_user_member = user_member_of_group?

    @sum = current_user.members.count { |member| member.status == "pending" }
  end

  def new
    @group = Group.new
    count = 0
    current_user.groups.each do |group|
      count += group.members.count { |member| member.status == "pending" }
    end
    @members_pending = count
    @sum = current_user.members.count { |member| member.status == "pending" }
  end

  def create
    @group = Group.new(params_group)
    @group.user = current_user
    if @group.save
      redirect_to group_path(@group)
    else
      render :new, status: unprocessable_entity
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def params_group
    params.require(:group).permit(:name, :user_id)
  end

  def user_member_of_group?
    current_user.member_ids.each do |id|
      result = @group.member_ids.include?(id)
      return true if result
    end
    return false
  end
end

app/views/groups/_form.html.erb
<h1 class="h1-new">New group</h1>

<div class="container-new">
  <%= simple_form_for(@group) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit group", class: "btn btn-dark" %>
    </div>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<h1 class="h1-groups"><%= @group.name %></h1>

<% if @group.user_id == current_user.id %>
  <h3 class="h3-groups">Welcome to your group</h3>
<% else %>
  <% if current_user.members.empty? == false %>
    <% if current_user.members.where(:status => "accepted").exists? %>
      <h3 class="h3-groups">Welcome to your group</h3>
    <% elsif current_user.members.where(:status => "accepted").exists? == false %>
      <%= simple_form_for [@group, @member] do |f| %>
        <%= f.submit "Heart", class: "btn btn-dark" %>
      <% end %>
    <% end %>
  <% else %>
    <%= simple_form_for [@group, @member] do |f| %>
      <%= f.submit "Heart", class: "btn btn-dark" %>
    <% end %>
  <% end %>
<% end %>


<h2>Members of the group</h2>
<%= link_to user_path(@group.user) do %>
    <div class="card-content card-container d-flex mt-3">
      <%= cl_image_tag @group.user.photos.first.key, class: "avatar" if @group.user.photos.attached? %>
      <div class="card-product-infos">
      <% if @group.user == current_user %>
        <h2 class="groups">Me</h2>
      <% else %>
        <h2 class="groups"><%= @group.user.first_name %></h2>
      <% end %>
        <p><%= @group.user.description %></p>
      </div>
    </div>
<% end %>

<% @group.members.each do |member| %>
  <% if member.status == "accepted" %>
    <%= link_to user_path(member.user) do %>
        <div class="card-content card-container d-flex mt-3">
          <%= cl_image_tag member.user.photos.first.key,class: "avatar" %>
          <div class="card-product-infos">
            <% if member.user == current_user %>
              <h2 class="groups">Me</h2>
            <% else %>
              <h2 class="groups"> <%= member.user.first_name%></h2>
            <% end %>
            <p><%= member.user.description %></p>
          </div>
        </div>
    <% end %>
  <% end %>
<% end %>


<% if @group.user_id == current_user.id %>
 <% if @group.chatroom == nil %>
 <div class="button-invite">
  <%= link_to "Create a new chat", new_group_chatroom_path(@group) %>
 </div>
 <% end %>
<% end %>

<% if current_user.members.empty? == false %>
  <% if current_user.members.first.group_id == @group.id && current_user.members.where(:status => "accepted").exists? %>
  <div class="button-invite">
    <%= link_to "Leave this group", group_member_path(@current_user.members.first), class: "btn", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>
  <% end %>
<% end %>