config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :members, only: [:new, :create, :destroy]
    resources :chatrooms, only: [:new, :create]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post "/users/:nickname/members/new", to: "members#new_member", as: "new_member_user"
  get '/users/:nickname', to: 'users#show', as: 'user'
  patch "/members/:id/accept", to: "members#accept", as: "accept"
  patch "/members/:id/reject", to: "members#reject", as: "reject"
  patch "/members/:id/check", to: "members#check", as: "check"
  get "/dashboard", to: "users#dashboard", as: "dashboard"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true, uniqueness: true
  # validates_format_of :email, :with[/\A\w+@\w+\.\w{2,3}\z/], message: "must be a valid email address"
  validates :password, presence: true, length: { minimum: 6 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :nickname, presence: true, uniqueness: true
  # validates_format_of :nickname, :with[/\A\w{4,16}\z/], message: "cannot contain spaces or special characters"
  validates :age, presence: true, numericality: { only_integer: true }
  validates :location, presence: true
  validates :gender, presence: true, inclusion: { in: %w(Male Female) }
  validates :description, presence: true, length: { minimum: 10 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many_attached :photos
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def show
    count = 0

    current_user.groups.each do |group|
      count += group.members.count { |member| member.status == "pending" }
    end
    @members_pending = count
    @sum = current_user.members.count { |member| member.status == "pending" }
  end

  def dashboard
    @user = current_user
    @groups = current_user.groups
    @members = current_user.members
    count = 0
    current_user.groups.each do |group|
      count += group.members.count { |member| member.status == "pending" }
    end
    @members_pending = count

    @sum = current_user.members.count { |member| member.status == "pending" }
  end

private

  def set_user
    @user = User.find(params[:nickname])
  end

  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :nickname, :age, :location, :gender, :description, :tags, :photo)
  end
end

app/views/users/dashboard.html.erb
<div class="pic-dashboard">
    <h3>Welcome back, </h3>
      <%= link_to user_path(current_user) do%>
        <%= cl_image_tag current_user.photos.first.key, height: 85, width: 85, crop: :fill if current_user.photos.attached? %>
      <% end %>
      <h1><%= current_user.first_name %> <%= current_user.last_name %></h1>
</div>




<% if current_user.groups.empty? && current_user.members.empty? == false %>
  <div class="dashboard-container">
    <h1>Manage Your Requests</h1>
    <% @members.each do |member| %>

      <% if member.invited == current_user.id %>
        <div class="dashboard-card1">
          <div class="top">
                <h5>Invitation to join:</h5>
                <h5>Status:</h5>
          </div>
          <div class="top">
                 <%= link_to user_path(member.group) do %>
                  <h6> <%= member.group.name %> </h5>
                 <% end %>
                <h6><%= member.status %></h6>
          </div>
           <div class="image1">
              <%= link_to user_path(member.group.user) do %>
                <%= cl_image_tag member.group.user.photos.first.key, height: 85, width: 85, crop: :fill if member.group.user.photos.attached? %>
              <% end %>
              <h5> Owned by <%= member.group.user.first_name %> <%= member.group.user.last_name %> <i class="fa-solid fa-house-chimney-user fa-xs" style="color: #583f91;"></i></h5>
              </div>
        </div>
      <% end %>
    <% end %>


    <% @members.each do |member| %>
      <% if member.invited != current_user.id %>
        <div class="dashboard-card1">
          <div class="top">
                <h5>Invitation to join:</h5>
                <h5>Status:</h5>
          </div>
          <div class="top">
                <h6> <%= link_to Group.find(member.group_id).name, group_path(Group.find(member.group_id)) %> </h6>
                <h6><%= member.status %></h6>
          </div>
           <div class="image1">
              <%= link_to user_path(Group.find(member.group_id).user) do %>
                <%= cl_image_tag Group.find(member.group_id).user.photos.first.key, height: 85, width: 85, crop: :fill if Group.find(member.group_id).user.photos.attached? %>
              <% end %>
              <h5> By <%= Group.find(member.group_id).user.first_name %> <%= Group.find(member.group_id).user.last_name %> <i class="fa-solid fa-house-chimney-user fa-xs" style="color: #583f91;"></i></h5>
            </div>
            <div class="link-top">
              <% if member.status == "pending" %>
                <div class="link-heart">
                <%= link_to accept_path(member), data: {turbo_method: :patch} do %> <i class="fa-solid fa-heart" style="color: #3b034f;"></i><% end %> <%= link_to reject_path(member), data: {turbo_method: :patch} do %><i class="fa-solid fa-rectangle-xmark" style="color: #3b034f;"></i><% end %>
                </div>
              <% end %>
              </div>
              <% if member.status == "pending" %>
                <h3 class="new">NEW</h3>
              <% end %>
        </div>
      <% end %>
  </div>
  <% end %>


 <div class="dashboard-container">
<% elsif current_user.groups.empty? == false && current_user.members.empty? %>

      <h1 class="h1-owner">Manage Your Requests</h1>
      <% @groups.each do |group| %>
        <% group.members.each do |member| %>
            <% if member.invited == current_user.id %>




          <div class="dashboard-card1">
            <div class="top">
                <h5>Invitation to:</h5>
                <h5>Status:</h5>
              </div>
               <div class="top">
                 <%= link_to user_path(member.user) do %>
                  <h6> <strong><%= member.user.first_name %> <%= member.user.last_name %></strong></h5>
                 <% end %>
                <h6><%= member.status %></h6>
              </div>
              <div class="image1">
              <%= link_to user_path(member.user) do %>
                <%= cl_image_tag member.user.photos.first.key, height: 85, width: 85, crop: :fill if member.user.photos.attached? %>
              <% end %>
              <h5> Was invited to your group <i class="fa-solid fa-house-chimney-user fa-xs" style="color: #583f91;"></i></h5>
              <% if member.status != "pending" && member.check == "no" %>
                <div class="new">
                <%= link_to check_path(member), data: {turbo_method: :patch} do %> New </i><% end %>
                </div>
              <% end %>
              </div>
          </div>





            <% else %>

            <div class="dashboard-card1">
              <div class="top">
                <h5>Invitation to:</h5>
                <h5>Status:</h5>
              </div>
               <div class="top">
                <h6><%= link_to member.group.name, group_path(member.group) %></h6>
                <h6><%= member.status %></h6>
              </div>
              <div class="image">
              <%= link_to user_path(member.user) do %>
                <%= cl_image_tag member.user.photos.first.key, height: 85, width: 85, crop: :fill if member.user.photos.attached? %>
              <% end %>
              <h5> <strong><%= member.user.first_name %> <%= member.user.last_name %></strong> <i class="fa-solid fa-house-chimney-user fa-xs" style="color: #583f91;"></i></h5>
              </div>
              <div class="bottom">
              <h6>Location * Gender * Age</h6>
              <p><%= member.user.location %> * <%= member.user.gender %> * <%= member.user.age %></p>
              <h6>Interests</h6>
              <div class="tags-list">
              <% member.user.tags.split(",").each do |tag| %>
                <ul>
                     <li><%=tag%></li>
                </ul>
              <% end %>
              </div>
              <h6>About me:</h6>
              <%= link_to "See more...", user_path(member.user) %>
              </div>
              <div class="link-top">
              <% if member.status == "pending" %>
                <div class="link-heart">
                <%= link_to accept_path(member), data: {turbo_method: :patch} do %> <i class="fa-solid fa-heart" style="color: #3b034f;"></i><% end %> <%= link_to reject_path(member), data: {turbo_method: :patch} do %><i class="fa-solid fa-rectangle-xmark" style="color: #3b034f;"></i><% end %>
                </div>
              <% end %>
              </div>
              <% if member.status == "pending" %>
                <h3 class="new">NEW</h3>
              <% end %>
            </div>
            <% end %>
        <% end %>
      <% end %>
<% end %>
</div>


<div class="dashboard-create">
  <% if current_user.groups.empty? && current_user.members.first == nil %>
    <h1>Create your group</h1>
    <%= link_to "Start", new_group_path %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show">
<div class="container d-flex justify-content-between">
 <div class="card-image">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
    </div>
  </div>
</div>
<div class="main w-100 m-0">
    <div class="main-image">
      <div class="mt-3">
      <div id="carouselExampleIndicators" class="carousel slide pointer-event" data-bs-interval="99999" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <% @user.photos.each_with_index do |photo, index| %>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-current="true" aria-label="Slide <%= index + 1 %>"></button>
          <% end %>
        </div>
        <div class="carousel-inner">
          <% @user.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <%= cl_image_tag photo.key, height: 400, width: 366, crop: :fill %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <div class="card-image-infos">
    <div>
      <h1><%=@user.first_name %> <%= @user.last_name %>, <%= @user.age %></h1>
       <h5><i class="fa-solid fa-location-dot" style="color: #6804fc;"></i>  Wants to live in <%= @user.location %></h5>
      <br>
      <div id="about-me">
      <h5>About me</h5>
      <p><%= @user.description %></p>
      </div>
      <br>
    <h4>Interests</h4>
    <div class="interests">
      <% @user.tags.split(",").each do |tag| %>
      <ul>
        <li>
          <%= tag %>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>
</div>

<div class="button-invite">
<% if @user.groups.empty? == false %>
  <%= link_to "Back to Group", group_path(@user.groups.first) %>
<% elsif @user.members.empty? == false %>
  <%= link_to "Back to Group", group_path(@user.members.first.group_id) %>
<% end %>
 </div>

<div class="container-show">
<br>
<% if current_user.groups.empty? == false %>
  <% if @user.groups.empty? == false %>
    <p></p>
  <% elsif @user.members.empty? == true %>
    <div class="button-invite">
    <%= button_to "Invite to your group",  new_member_user_path(@user.nickname), method: :post %>
    </div>
  <% elsif @user.members.first.status != "accepted" %>
    <div class="button-invite">
    <%= button_to "Invite to your group",  new_member_user_path(@user.nickname), method: :post %>
    </div>
  <% end %>
<% end %>
<br>
</div>
</div>