config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :groups, only: [:new, :create, :show, :destroy] do
    resources :members, only: [:new, :create, :destroy]
    resources :chatrooms, only: [:new, :create]
  end
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  post "/users/:nickname/members/new", to: "members#new_member", as: "new_member_user"
  get '/users/:nickname', to: 'users#show', as: 'user'
  patch "/members/:id/accept", to: "members#accept", as: "accept"
  patch "/members/:id/reject", to: "members#reject", as: "reject"
  patch "/members/:id/check", to: "members#check", as: "check"
  get "/dashboard", to: "users#dashboard", as: "dashboard"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if user_signed_in? %>
  <div class="footer">
    <div class="footer-links" data-controller="footer-style">

             <%= link_to root_path, data: { footer_style_target: "link" } do %> <i class="fa-solid fa-house-user"></i><% end %>


            <% if current_user.groups.first == nil %>
                <% if current_user.members.first != nil %>
                    <% if current_user.members.first.status == "accepted" %>

                        <%= link_to group_path(current_user.members.first.group_id), data: { footer_style_target: "link" } do %> <i class="fa-solid fa-users"></i> <% end %>

                    <% end %>
                <% end %>
            <% end %>

            <% if current_user.groups.first != nil %>
                      <% if current_user.groups.first["user_id"] == current_user.id %>

                          <%= link_to group_path(current_user.groups.first), data: { footer_style_target: "link" } do %> <i class="fa-solid fa-users"></i> <% end %>

                      <% end %>
            <% end %>

            <% if current_user.groups.first == nil %>
                <% if current_user.members.first != nil %>
                    <% if current_user.members.first.status == "accepted" %>
                      <% if Group.find(current_user.members.first.group_id).chatroom != nil  %>
                        <%= link_to chatroom_path(Group.find(current_user.members.first.group_id).chatroom), data: { footer_style_target: "link" } do %> <i class="fa-solid fa-comments"></i><% end %>
                      <% end %>
                    <% end %>
                <% end %>
            <% end %>

            <% if current_user.groups.first != nil %>
                      <% if current_user.groups.first["user_id"] == current_user.id %>
                        <% if current_user.groups.first.chatroom != nil %>

                            <%= link_to chatroom_path(current_user.groups.first.chatroom), data: { footer_style_target: "link" } do %> <i class="fa-solid fa-comments"></i><% end %>

                        <% end %>
                      <% end %>
            <% end %>



            <div class="notification">
              <% if current_user %>
                <%= link_to dashboard_path, data: { footer_style_target: "link" } do %> <i class="fa-solid fa-user"></i><% end %>
                <% if @members_pending != 0 %>
                <%= link_to  dashboard_path do %> <i id="button-green" class="fa-solid fa-circle fa-2xs" style="color: #4cf349;"></i> <% end %>
                <% end %>
                <%= link_to  "#{@sum}", "/dashboard", class: "nav-link" if  @sum != 0 %>
              <% end %>
            </div>

     </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-main">
  <div class="card-navbar d-flex align-itens-center justify-content-center">
    <i class="fa-solid fa-house-chimney-user fa-xl" style="color: #583f91;"></i>
    <mark class="red m-0">ROOM</mark>
    <mark class="blue m-0">MATE</mark>
  </div>

  <div class="ul-navbar">
    <ul>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>